### ISSUE TITLE
Unique slug in different trees

### ISSUE THREAD

**Issue by mesemus** [oarepo/flask-taxonomies#12]
It is possible to create multiple taxonomies, each in its own subtree. 
For the sake of readability iIt would be nice to split the Taxonomy into two models:

Taxonomy (code:str, metadata: json)
TaxonomyTerm(...same props as the current taxonomy, taxonomy=ForeignKey(Taxonomy))

The urls would look as ....<taxonomy.code>/<taxonomyterm.slug>/.../<taxonomyterm.slug>

The slugs then need not be unique across taxonomies.

**Comment by mirekys** [comment]
Models has been split [here](https://github.com/oarepo/flask-taxonomies/blob/taxonomy-term-split/flask_taxonomies/models.py), but I still need to update the views (URLs) to match new models
