### ISSUE TITLE
path is not resolved correctly

### ISSUE THREAD

**Issue by Semtexcz** [oarepo/flask-taxonomies#30]
Request: 
GET /api/taxonomies/provider/?drilldown=True HTTP/1.1
Host: 127.0.0.1:5000
Accept: application/json
User-Agent: PostmanRuntime/7.15.2
Cache-Control: no-cache
Postman-Token: 2400bb55-7941-4cd9-bd0f-727bc8b048ed,64a310ca-bcf3-461a-8279-132c2abe0aa7
Host: 127.0.0.1:5000
Accept-Encoding: gzip, deflate
Connection: keep-alive
cache-control: no-cache

returns:
[
  {
    "children": [
      {
        "children": [
          {
            "address": "Královopolská 147, 612 00 Brno",
            "id": 8207,
            "lib_url": "http://arub.avcr.cz/knihovna/",
            "links": {
              "self": "https://127.0.0.1:5000/api/taxonomies/provider/research/avcr/archeologicky_ustav_brno/",
              "tree": "https://127.0.0.1:5000/api/taxonomies/provider/research/avcr/archeologicky_ustav_brno/?drilldown=True"
            },
            "name": [
              {
                "lang": "cze",
                "name": "Archeologický ústav, Brno"
              }
            ],
            **"path": "/{taxonomy.code}/research/avcr/archeologicky_ustav_brno",**
            "slug": "archeologicky_ustav_brno",
            "url": "http://www.arub.cz/"
          }, etc....................................

Path is not correctly resolved.

**Comment by mirekys** [comment]
@Semtexcz should be working now ;)
