### ISSUE TITLE
TaxonomyTerm.link_self in marshmallow.__init__.py:convert ref returns Error

### ISSUE THREAD

**Issue by Semtexcz** [oarepo/flask-taxonomies#34]
Traceback:

test_marshmallow.py:218: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../venv/lib/python3.7/site-packages/marshmallow/schema.py:588: in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
../../venv/lib/python3.7/site-packages/marshmallow/schema.py:670: in _do_load
    index_errors=self.opts.index_errors,
../../venv/lib/python3.7/site-packages/marshmallow/marshalling.py:290: in deserialize
    index=(index if index_errors else None)
../../venv/lib/python3.7/site-packages/marshmallow/marshalling.py:62: in call_and_store
    value = getter_func(data)
../../venv/lib/python3.7/site-packages/marshmallow/marshalling.py:283: in <lambda>
    data
../../venv/lib/python3.7/site-packages/marshmallow/fields.py:265: in deserialize
    output = self._deserialize(value, attr, data)
../../venv/lib/python3.7/site-packages/marshmallow/fields.py:468: in _deserialize
    data, errors = self.schema.load(value)
../../venv/lib/python3.7/site-packages/marshmallow/schema.py:588: in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
../../venv/lib/python3.7/site-packages/marshmallow/schema.py:658: in _do_load
    original_data=data)
../../venv/lib/python3.7/site-packages/marshmallow/schema.py:866: in _invoke_load_processors
    data=data, many=many, original_data=original_data)
../../venv/lib/python3.7/site-packages/marshmallow/schema.py:969: in _invoke_processors
    data = utils.if_none(processor(data), data)
../../flask-taxonomies/flask_taxonomies/marshmallow/__init__.py:49: in convert_ref
    in_data["links"]["self"] = term.link_self
../../flask-taxonomies/flask_taxonomies/models.py:105: in link_self
    _external=True,
../../venv/lib/python3.7/site-packages/flask/helpers.py:356: in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
../../venv/lib/python3.7/site-packages/flask/app.py:2080: in handle_url_build_error
    reraise(exc_type, exc_value, tb)
../../venv/lib/python3.7/site-packages/flask/_compat.py:36: in reraise
    raise value
../../venv/lib/python3.7/site-packages/flask/helpers.py:345: in url_for
    force_external=external)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <werkzeug.routing.MapAdapter object at 0x7fe0ff584a58>
endpoint = 'taxonomies.taxonomy_get_term'
values = {'taxonomy_code': 'provider', 'term_path': 'edu/public_uni/univerzita_karlova_v_praze'}
method = None, force_external = True, append_unknown = True

    def build(
        self,
        endpoint,
        values=None,
        method=None,
        force_external=False,
        append_unknown=True,
    ):
        """Building URLs works pretty much the other way round.  Instead of
        `match` you call `build` and pass it the endpoint and a dict of
        arguments for the placeholders.
    
        The `build` function also accepts an argument called `force_external`
        which, if you set it to `True` will force external URLs. Per default
        external URLs (include the server name) will only be used if the
        target URL is on a different subdomain.
    
        >>> m = Map([
        ...     Rule('/', endpoint='index'),
        ...     Rule('/downloads/', endpoint='downloads/index'),
        ...     Rule('/downloads/<int:id>', endpoint='downloads/show')
        ... ])
        >>> urls = m.bind("example.com", "/")
        >>> urls.build("index", {})
        '/'
        >>> urls.build("downloads/show", {'id': 42})
        '/downloads/42'
        >>> urls.build("downloads/show", {'id': 42}, force_external=True)
        'http://example.com/downloads/42'
    
        Because URLs cannot contain non ASCII data you will always get
        bytestrings back.  Non ASCII characters are urlencoded with the
        charset defined on the map instance.
    
        Additional values are converted to unicode and appended to the URL as
        URL querystring parameters:
    
        >>> urls.build("index", {'q': 'My Searchstring'})
        '/?q=My+Searchstring'
    
        When processing those additional values, lists are furthermore
        interpreted as multiple values (as per
        :py:class:`werkzeug.datastructures.MultiDict`):
    
        >>> urls.build("index", {'q': ['a', 'b', 'c']})
        '/?q=a&q=b&q=c'
    
        Passing a ``MultiDict`` will also add multiple values:
    
        >>> urls.build("index", MultiDict((('p', 'z'), ('q', 'a'), ('q', 'b'))))
        '/?p=z&q=a&q=b'
    
        If a rule does not exist when building a `BuildError` exception is
        raised.
    
        The build method accepts an argument called `method` which allows you
        to specify the method you want to have an URL built for if you have
        different methods for the same endpoint specified.
    
        .. versionadded:: 0.6
           the `append_unknown` parameter was added.
    
        :param endpoint: the endpoint of the URL to build.
        :param values: the values for the URL to build.  Unhandled values are
                       appended to the URL as query parameters.
        :param method: the HTTP method for the rule if there are different
                       URLs for different methods on the same endpoint.
        :param force_external: enforce full canonical external URLs. If the URL
                               scheme is not provided, this will generate
                               a protocol-relative URL.
        :param append_unknown: unknown parameters are appended to the generated
                               URL as query string argument.  Disable this
                               if you want the builder to ignore those.
        """
        self.map.update()
    
        if values:
            if isinstance(values, MultiDict):
                temp_values = {}
                # iteritems(dict, values) is like `values.lists()`
                # without the call or `list()` coercion overhead.
                for key, value in iteritems(dict, values):
                    if not value:
                        continue
                    if len(value) == 1:  # flatten single item lists
                        value = value[0]
                        if value is None:  # drop None
                            continue
                    temp_values[key] = value
                values = temp_values
            else:
                # drop None
                values = dict(i for i in iteritems(values) if i[1] is not None)
        else:
            values = {}
    
        rv = self._partial_build(endpoint, values, method, append_unknown)
        if rv is None:
>           raise BuildError(endpoint, values, method, self)
E           **werkzeug.routing.BuildError: Could not build url for endpoint 'taxonomies.taxonomy_get_term' with values ['taxonomy_code', 'term_path']. Did you mean 'invenio_jsonschemas.get_schema' instead?**

../../venv/lib/python3.7/site-packages/werkzeug/routing.py:2007: BuildError

**Comment by mesemus** [comment]
Probably fixed, test works
